<div id="closest-list">
	<p><?=$this->__('Closed store');?>:</p>
	<ul>
	
	<table cellpadding="0" cellspacing="0" border="0" width="100%">
		<tbody>
	

	<?php
		$stores = $this->getStores();
		if (count($stores)) {

			foreach($stores as $store) {
			?>
			<tr>
				<td width="325" height="25"><a href="<?=$this->getUrl('winkels/details/index/').'view/'.$store->getCustomUrl();?>"><?=$store->getCity();?></a></td>
				<td><a href="<?=$this->getUrl('winkels/details/index/view/').$store->getCustomUrl();?>?search=<?= $this->getRequest()->getParam("criteria")?>">Route</a> | <a href="<?=$this->getUrl('winkels/details/index/').'view/'.$store->getCustomUrl();?>">Openingstijden</a></td>
			</tr>

			<?
			}
		}
	?>
		</tbody>
	</table>
</div>
<script type="text/javascript">
<!--//--><![CDATA[//><!--
	var markers = [<?=$this->getMarkers();?>];
//--><!]]>
</script>