<?php
/**
 * Magento Ogone Payment extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Mage_Ogone
 * @copyright  Copyright (c) 2008 ALTIC Charly Clairmont (CCH)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @file	   Ogone/info/Ogone.phtml
 */
?>
<?php if($_info = $this->getInfo()): ?>
<p>Paiement sécurisé avec Ogone </p>
<?php if($_info->getPaymentMethod()){ ?>
<p>type de carte : <?php echo $_info->getPaymentMethod()->getValue(); ?></p>
<p>Opérateur : <?php echo $_info->getPaymentMethod()->getBrand(); ?></p>
<?php } ?>
<?php else: ?>
<?php endif; ?>
