<h1><?=$this->__('Your order');?></h1>
<div id="wizard-cart" class="wizard-block cart content-block">
    <div class="wizard-block-content clearfix">
		<h2 class="wizard-block-step"><span>1</span> <?php echo $this->__('Shopping Cart') ?></h2>
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

		<? $topmethods = $this->getChildHtml('top_methods'); ?>
        <?php if(!$this->hasError() && $topmethods): ?>
        <ul class="checkout-types">
            <?php echo $topmethods; ?>
        </ul>
        <?php endif; ?>

		<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
			<fieldset>
				<table id="shopping-cart-table" class="data-table cart-table">
				<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
					<col class="p-image" />
					<col class="p-name" />
					<col class="p-size" />
					<col class="p-price" />
					<col class="p-qty" />
					<col class="p-subtotal" />
					<thead>
						<tr>
							<th rowspan="<?php echo $mergedCells; ?>" class="p-image"><?php echo $this->__('Acticles') ?></th>
							<th rowspan="<?php echo $mergedCells; ?>" class="p-name"><span><?php //echo $this->__('Product Name') ?></span></th>
							<th rowspan="<?php echo $mergedCells; ?>" class="p-size"><?php echo $this->__('Product size') ?></th>
							<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
							<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Move to Wishlist') ?></th>
							<?php endif ?>
							<th colspan="<?php echo $mergedCells; ?>" class="p-price"><?php echo $this->__('Unit Price') ?></th>
							<th rowspan="<?php echo $mergedCells; ?>" class="p-qty"><?php echo $this->__('Qty') ?></th>
							<th colspan="<?php echo $mergedCells; ?>" class="p-subtotal"><?php echo $this->__('Subtotal product') ?></th>
							<th colspan="<?php echo $mergedCells; ?>" class="p-delete structural"><?php echo $this->__('Remove item') ?></th>
						</tr>
						<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
						<tr>
							<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
							<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
							<th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
							<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
						</tr>
						<?php endif; ?>
					</thead>
					<tbody>
					<?php foreach($this->getItems() as $_item): ?>
						<?php echo $this->getItemHtml($_item) ?>
					<?php endforeach ?>
					</tbody>
				</table>
				<p id="update-cart-wrap">
					<button type="submit" class="button">
						<?php echo $this->__('Update Shopping Cart') ?>
					</button>
				</p>
				<script type="text/javascript">decorateTable('shopping-cart-table')</script>
			</fieldset>
		</form>
		<div class="col2-set cart-collaterals">
			<div class="col-1">
				<?php echo $this->getChildHtml('crosssell') ?>
			</div>
			<div class="col-2">
				<?php echo $this->getChildHtml('coupon') ?>
				<?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
			</div>
		</div>
		<div class="totals">
			<?php echo $this->getChildHtml('totals'); ?>

			<?php $methods = $this->getChildHtml('methods'); ?>
			<?php if(!$this->hasError() && $methods): ?>
			<ul class="checkout-types">
				<?php echo $methods; ?>
			</ul>
			<?php endif; ?>
		</div>
		<ul class="footer-buttons">
			<?php if($this->getContinueShoppingUrl()): ?>
			<li class="continue-shopping"><a href="<?php echo $this->getContinueShoppingUrl() ?>">&lt; <?php echo $this->__('Continue Shopping') ?></a></li>
			<?php endif; ?>
			<li class="continue-order"><a href="<?php echo $this->getUrl('checkout/wizard') ?>" class="as-button"><?=$this->__('Continue my order');?></a></li>
			<li class="continue-order top-button"><a href="<?php echo $this->getUrl('checkout/wizard') ?>" class="as-button"><?=$this->__('Continue my order');?></a></li>
		</ul>
	</div>
</div>
