<?php
$form = Mage::helper('customer')->isLoggedIn() ? $this->getCustomer() : new Varien_Object(Mage::getSingleton('customer/session')->getCustomerFormData());
$wizardHelper = Mage::helper('wizard');
?>
<fieldset class="customer-data content-block">
	<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
	<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
	<h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
	<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
	<p class="clearfix gender">
		<?php if ($_gender->isEnabled()): ?>
			<?php echo $_gender->setGender($form->getGender())->toHtml() ?>
		<?php endif ?>
	</p>
	<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($form)->toHtml() ?>
	<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
	<?php if ($_dob->isEnabled() && !$wizardHelper->isLoggedInWizard()): ?>
		<?php echo $_dob->setDate($form->getDob())->toHtml() ?>
	<?php endif ?>
	<?php if(!$wizardHelper->isLoggedInWizard()): ?>
    	<p>
    		<label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
    		<input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($form->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
    	</p>
	<?php endif; ?>
	<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
	<?php if ($_taxvat->isEnabled()): ?>
		<?php echo $_taxvat->setTaxvat($form->getTaxvat())->toHtml() ?>
	<?php endif ?>
	<?php $customerAttributes = $this->getChild('customer_form_user_attributes');?>
	<?php if ($customerAttributes): ?>
		<?php $customerAttributes->setShowContainer(false);?>
		<?php $this->restoreSessionData($customerAttributes->getForm());?>
		<?php echo $customerAttributes->toHtml()?>
	<?php endif;?>
</fieldset>