   <div class="login-register-choice clearfix">
        <div id="login-choice">
            <h3><?php echo $this->__('Are you placing an order for the first time?') ?></h3>
            <p class="cms-content"><?php echo $this->__('Push the continue button to start your order. If you already have an account, you can use it to login and continue directly with your order.') ?></p>
            <p class="footer">
                <a href="<?php echo $this->getUrl('checkout/wizard/billing')?>" id="continue-order" class="as-button button-arrow"><?php echo $this->__('Continue my order');?></a>
            </p>
        </div>

        <div id="register-choice">
            <h3><?php echo $this->__('Ive placed an order here before') ?></h3>
            <p class="cms-content"><?php echo $this->__('Login and your account will be retrieved') ?></p>
            <form action="<?php echo $this->getUrl('checkout/wizard/loginPost')?>" method="post" class="theme1 account-login">
                <fieldset>
                    <p>
                        <label for="login-email"><?=$this->__('Email Address');?></label>
                            <input type="text" name="login[username]" size="20" id="login-email" class="input-text required-entry validate-email" value="" />
                    </p>
                    <p>
                        <label for="login-password"><?=$this->__('Password');?></label>
                            <input type="password" name="login[password]" size="20" id="login-password" class="input-text required-entry" />
                    </p>
                    <p class="footer">
                        <button type="submit" class="button-arrow"><?=$this->__('Continue my order');?></button>
                    </p>
                </fieldset>
            </form>
            <script type="text/javascript">
            //<![CDATA[
                var dataForm = new VarienForm('wizard-login');
            //]]>
            </script>
        </div>
    </div>