<?php if ($this->isNewsletterEnabled()): ?>
<div class="content-block clearfix subscription theme1">
	<h3 class="block-title"><?=$this->__('Newsletter Subscription'); ?></h3>
	<p>
		<label for="subscription"><?php echo $this->__('General Subscription') ?></label>
		<input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
	</p>
</div>
<?php endif; ?>