<?php $_element = $this->getElement() ?>
<?php $this->checkFieldDisable() ?>

<?php if ($_element->getType()=='hidden'): ?>
<tr>
    <td class="hidden" colspan="100"><?php echo trim($_element->getElementHtml()) ?></td>
</tr>
<?php else: ?>
<tr>
    <td class="label"><?php echo trim($this->getElementLabelHtml()) ?></td>
    <td class="value"><?php echo trim($this->getElementHtml()) ?></td>
    <td class="scope-label"><?php echo $this->getScopeLabel() ?></td>
    <?php if ($this->canDisplayUseDefault()): ?>
    <td class="value use-default">
        <input type="checkbox" name="use_default[]" id="<?php echo $_element->getHtmlId() ?>_default"<?php if ($this->usedDefault()): ?> checked="checked"<?php endif; ?> onclick="toggleValueElements(this, this.parentNode.parentNode)" value="<?php echo $this->getAttributeCode() ?>"/>
        <label for="<?php echo $_element->getHtmlId() ?>_default" class="normal"><?php echo $this->__('Use Default Value') ?></label>
    </td>
    <?php endif; ?>
    <td<?php if ($_element->getNote()): ?> class="note"<?php endif ?>><small><?php echo $_element->getNote()?$_element->getNote():'&nbsp;' ?></small></td>
</tr>
<?php endif; ?>