<div id="vacancy-apply">
    <?php
    $vacancy = $this->getVacancy();
    $errors = $this->getVacancyApplyErrors();
    $formType = $vacancy['vacancy_form_type'];
    ?>
    <h2><?=$this->__('Apply for this job');?></h2>
    <form method="post" enctype="multipart/form-data" action="" class="theme1">
        <?php if(!empty($errors)):?>
        <p class="errors-message">
            <?=$this->__('One of the required fields is not, or not correclty filled in.');?>
        </p>
        <?php endif;?>
        <?php
        if(!empty($errors['invalid']) && $errors['invalid'] == 'cv'):?>
        <p class="errors-message">
            <?=$this->__('The selected cv file is invalid. Select another one or contact us if you think your file is valid.');?>
        </p>
        <?php endif;?>

        <?php if($formType == 2):?>
        <?php $stores = $this->getStores(); ?>
        <p>
            <label for="preferred-store-1" class="first"><?=$this->__('1ste voorkeurplaats');?>*:</label>
            <select name="preferred-store-1" id="preferred-store-1">
                <?php foreach($stores as $store):?>
                <option value="<?=$store->getId();?>" <?=($this->getPostValue('preferred-store-1',$vacancy['store_id']) == $store->getId() ? 'selected="selected"' : '');?>><?=$store->getName();?></option>
                <?php endforeach;?>
            </select>
        </p>
        <p>
            <label for="preferred-store-2" class="first"><?=$this->__('2e voorkeurplaats');?>:</label>
            <select name="preferred-store-2" id="preferred-store-2">
                <option value=""><?=$this->__('Make a choice');?></option>
                <?php foreach($stores as $store):?>
                <option value="<?=$store->getId();?>" <?=($this->getPostValue('preferred-store-2') == $store->getId() ? 'selected="selected"' : '');?>><?=$store->getName();?></option>
                <?php endforeach;?>
            </select>
        </p>
        <p>
            <label for="preferred-store-3" class="first"><?=$this->__('3e voorkeurplaats');?>:</label>
            <select name="preferred-store-3" id="preferred-store-3">
                <option value=""><?=$this->__('Make a choice');?></option>
                <?php foreach($stores as $store):?>
                <option value="<?=$store->getId();?>" <?=($this->getPostValue('preferred-store-3') == $store->getId() ? 'selected="selected"' : '');?>><?=$store->getName();?></option>
                <?php endforeach;?>
            </select>
        </p>
        <h3><?=$this->__('Availabillity');?></h3>
        <p>
            <label for="available-from" class="first"><?=$this->__('available-from');?>:</label>
            <input type="text" name="available-from" class="input-text <?=$this->hasErrorsClass('available-from');?>" id="available-from" value="<?=$this->getPostValue('available-from');?>" />
            [dd-mm-jjjj]
        </p>
        <div class="form-row">
            <label for="available-days" class="first"><?=$this->__('available-days');?>:</label>
            <ul id="available-days-container">
                <?php for($i = 1; $i <= 7; $i++):?>
                <?php $day = strftime('%A', mktime(0, 0, 0, 1, $i, 2007))?>
                <li>
                    <input type="checkbox" name="available-days[]" id="available-days-<?=$i?>" value="<?=ucfirst($day);?>" <?=(in_array($day, $this->getPostValue('available-days', array())) ? 'checked="checked"' : '')?>>
                    <label for="available-days-<?=$i?>"><?=$day;?></label>
                </li>
                <?php endfor;?>
            </ul>
        </div>
        <?php endif;?>

        <p>
            <label class="inline"><?=$this->__('Gender');?>:*</label>
            <input type="radio" name="gender" id="gender-male" value="male" <?=($this->getPostValue('gender') == 'male' ? 'checked="checked"' : '');?> />
            <label for="gender-male" class="inline"><?=$this->__('Male');?></label>

            <input type="radio" name="gender" id="gender-female" value="female" <?=($this->getPostValue('gender') == 'female' ? 'checked="checked"' : '');?> />
            <label for="gender-female" class="inline"><?=$this->__('Female');?></label>
        </p>

        <p id="initials-wrap" class="inline">
            <label for="initials" class="first"><?=$this->__('Initials');?>:*</label>
            <input type="text" name="initials" class="input-text <?=$this->hasErrorsClass('initials');?>" id="initials" value="<?=$this->getPostValue('initials');?>" />
		</p>
		<p id="firstname-wrap" class="inline end">
            <label for="first-name"><?=$this->__('First name');?>:*</label>
            <input type="text" name="first-name" class="input-text <?=$this->hasErrorsClass('first-name');?>" id="first-name" value="<?=$this->getPostValue('first-name');?>" />
        </p>
        <p class="newline">
            <label for="last-name" class="first"><?=$this->__('Last name');?>:*</label>
            <input type="text" name="last-name" class="input-text <?=$this->hasErrorsClass('last-name');?>" id="last-name" value="<?=$this->getPostValue('last-name');?>" />
        </p>
        <p>
            <label for="vacancy-street" class="first"><?=$this->__('Street');?>:*</label>
            <input type="text" name="street" class="input-text <?=$this->hasErrorsClass('street');?>" id="vacancy-street" value="<?=$this->getPostValue('street');?>" />
		</p>
		<p id="number-wrap" class="inline">
            <label for="vacancy-number"><?=$this->__('Nr.');?>:*</label>
            <input type="text" name="number" class="input-text <?=$this->hasErrorsClass('number');?>" id="vacancy-number" value="<?=$this->getPostValue('number');?>" />
		</p>
		<p id="number-addition-wrap" class="inline">
            <label for="number-addition"><?=$this->__('Addition');?>:</label>
            <input type="text" name="number-addition" class="input-text <?=$this->hasErrorsClass('number-addition');?>" id="number-addition" value="<?=$this->getPostValue('number-addition');?>" />
        </p>
        <p id="zip-wrap" class="inline newline">
            <label for="vacancy-postcode" class="first"><?=$this->__('Postcode');?>:*</label>
            <input type="text" name="postcode" class="input-text <?=$this->hasErrorsClass('postcode');?>" id="vacancy-postcode" value="<?=$this->getPostValue('postcode');?>" />
		</p>
		<p id="city-wrap" class="inline end">
            <label for="vacancy-city"><?=$this->__('City');?>:*</label>
            <input type="text" name="city" class="input-text <?=$this->hasErrorsClass('city');?>" id="vacancy-city" value="<?=$this->getPostValue('city');?>" />
        </p>
        <p class="newline">
            <label for="vacancy-country" class="first"><?=$this->__('Country');?>:</label>
            <select name="country" id="vacancy-country">
                <option value="Nederland" <?=($this->getPostValue('country') == 'Nederland' ? 'selected="selected"' : '');?>>Nederland</option>
                <option value="Belgie" <?=($this->getPostValue('country') == 'Belgie' ? 'selected="selected"' : '');?>>Belgi&euml;</option>
                <option value="Duitsland" <?=($this->getPostValue('country') == 'Duitsland' ? 'selected="selected"' : '');?>>Duitsland</option>
            </select>
        </p>
        <p id="birthdate-wrap">
            <label for="birth-date" class="first"><?=$this->__('birth-date');?> (DD-MM-JJJJ):</label>
            <input type="text" name="birth-date" class="input-text <?=$this->hasErrorsClass('birth-date');?>" id="birth-date" value="<?=$this->getPostValue('birth-date');?>" />
        </p>
        <p>
            <label for="vacancy-phone" class="first"><?=$this->__('phone');?>:</label>
            <input type="text" name="phone" class="input-text <?=$this->hasErrorsClass('phone');?>" id="vacancy-phone" value="<?=$this->getPostValue('phone');?>" />
        </p>
        <p>
            <label for="vacancy-phone-mobile" class="first"><?=$this->__('phone-mobile');?>:</label>
            <input type="text" name="phone-mobile" class="input-text <?=$this->hasErrorsClass('phone-mobile');?>" id="vacancy-phone-mobile" value="<?=$this->getPostValue('phone-mobile');?>" />
        </p>
        <p>
            <label for="vacancy-email" class="first"><?=$this->__('E-mail');?>:*</label>
            <input type="text" name="email" class="input-text <?=$this->hasErrorsClass('email');?>" id="vacancy-email" value="<?=$this->getPostValue('email');?>" />
        </p>

        <?php if($formType == 2):?>
        <h3><?=$this->__('Trainings');?></h3>
        <p>
            <label for="vacancy-training-1" class="first"><?=$this->__('training-1');?>:</label>
            <input type="text" name="training-1" class="input-text <?=$this->hasErrorsClass('training-1');?>" id="vacancy-training-1" value="<?=$this->getPostValue('training-1');?>" />

            <label for="vacancy-training-1-start"><?=$this->__('from');?>:</label>
            <input type="text" name="training-1-start" class="input-text <?=$this->hasErrorsClass('training-1-start');?>" id="vacancy-training-1-start" value="<?=$this->getPostValue('training-1-start');?>" />

            <label for="vacancy-training-1-end"><?=$this->__('to');?>:</label>
            <input type="text" name="training-1-end" class="input-text <?=$this->hasErrorsClass('training-1-end');?>" id="vacancy-training-1-end" value="<?=$this->getPostValue('training-1-end');?>" />
        </p>
        <p>
            <span class="first"><?=$this->__('training-1-completed');?>:</span>
            <input type="radio" name="training-1-completed" id="training-1-completed-yes" value="yes" <?=($this->getPostValue('training-1-completed') == 'yes' ? 'checked="checked"' : '');?> />
            <label for="training-1-completed-yes"><?=$this->__('Yes');?></label>

            <input type="radio" name="training-1-completed" id="training-1-completed-no" value="no" <?=($this->getPostValue('training-1-completed') == 'no' ? 'checked="checked"' : '');?> />
            <label for="training-1-completed-no"><?=$this->__('No');?></label>
        </p>
        <p>
            <label for="vacancy-training-2" class="first"><?=$this->__('training-2');?>:</label>
            <input type="text" name="training-2" class="input-text <?=$this->hasErrorsClass('training-2');?>" id="vacancy-training-1" value="<?=$this->getPostValue('training-2');?>" />

            <label for="vacancy-training-2-start"><?=$this->__('from');?>:</label>
            <input type="text" name="training-2-start" class="input-text <?=$this->hasErrorsClass('training-2-start');?>" id="vacancy-training-2-start" value="<?=$this->getPostValue('training-2-start');?>" />

            <label for="vacancy-training-2-end"><?=$this->__('to');?>:</label>
            <input type="text" name="training-2-end" class="input-text <?=$this->hasErrorsClass('training-2-end');?>" id="vacancy-training-2-end" value="<?=$this->getPostValue('training-2-end');?>" />
        </p>
        <p>
            <span class="first"><?=$this->__('training-2-completed');?>:</span>
            <input type="radio" name="training-2-completed" id="training-2-completed-yes" value="yes" <?=($this->getPostValue('training-2-completed') == 'yes' ? 'checked="checked"' : '');?> />
            <label for="training-2-completed-yes"><?=$this->__('Yes');?></label>

            <input type="radio" name="training-2-completed" id="training-2-completed-no" value="no" <?=($this->getPostValue('training-2-completed') == 'no' ? 'checked="checked"' : '');?> />
            <label for="training-2-completed-no"><?=$this->__('No');?></label>
        </p>
        <h3><?=$this->__('Work experience');?></h3>
        <p>
            <label for="vacancy-experience-1-company" class="first"><?=$this->__('experience-1-company');?>:</label>
            <input type="text" name="experience-1-company" class="input-text <?=$this->hasErrorsClass('experience-1-company');?>" id="vacancy-experience-1-company" value="<?=$this->getPostValue('experience-1-company');?>" />

            <label for="vacancy-experience-1-start"><?=$this->__('from');?>:</label>
            <input type="text" name="experience-1-start" class="input-text <?=$this->hasErrorsClass('experience-1-start');?>" id="vacancy-experience-1-start" value="<?=$this->getPostValue('experience-1-start');?>" />

            <label for="vacancy-experience-1-end"><?=$this->__('to');?>:</label>
            <input type="text" name="experience-1-end" class="input-text <?=$this->hasErrorsClass('experience-1-end');?>" id="vacancy-experience-1-end" value="<?=$this->getPostValue('experience-1-end');?>" />
        </p>
        <p>
            <label for="vacancy-experience-1-function" class="first"><?=$this->__('experience-1-function');?>:</label>
            <input type="text" name="experience-1-function" class="input-text <?=$this->hasErrorsClass('experience-1-function');?>" id="vacancy-experience-1-function" value="<?=$this->getPostValue('experience-1-function');?>" />
        </p>
        <p>
            <label for="vacancy-experience-2-company" class="first"><?=$this->__('experience-2-company');?>:</label>
            <input type="text" name="experience-2-company" class="input-text <?=$this->hasErrorsClass('experience-2-company');?>" id="vacancy-experience-2-company" value="<?=$this->getPostValue('experience-2-company');?>" />

            <label for="vacancy-experience-2-start"><?=$this->__('from');?>:</label>
            <input type="text" name="experience-2-start" class="input-text <?=$this->hasErrorsClass('experience-2-start');?>" id="vacancy-experience-2-start" value="<?=$this->getPostValue('experience-2-start');?>" />

            <label for="vacancy-experience-2-end"><?=$this->__('to');?>:</label>
            <input type="text" name="experience-2-end" class="input-text <?=$this->hasErrorsClass('experience-2-end');?>" id="vacancy-experience-2-end" value="<?=$this->getPostValue('experience-2-end');?>" />
        </p>
        <p>
            <label for="vacancy-experience-2-function" class="first"><?=$this->__('experience-2-function');?>:</label>
            <input type="text" name="experience-2-function" class="input-text <?=$this->hasErrorsClass('experience-2-function');?>" id="vacancy-experience-2-function" value="<?=$this->getPostValue('experience-2-function');?>" />
        </p>
        <h3><?=$this->__('Strong and weak points');?></h3>
        <p>
            <label for="vacancy-properties-strong" class="first"><?=$this->__('properties-strong');?>:</label>
            <input type="text" name="properties-strong" class="input-text <?=$this->hasErrorsClass('properties-strong');?>" id="vacancy-properties-strong" value="<?=$this->getPostValue('properties-strong');?>" />
        </p>
        <p>
            <label for="vacancy-properties-weak" class="first"><?=$this->__('properties-weak');?>:</label>
            <input type="text" name="properties-weak" class="input-text <?=$this->hasErrorsClass('properties-weak');?>" id="vacancy-properties-weak" value="<?=$this->getPostValue('properties-weak');?>" />
        </p>
        <?php endif;?>

        <p id="vacancy-motivation-upload">
            <label for="motivation-upload" class="first"><?=$this->__('Upload motivation');?>:</label>
            <input type="file" name="motivation-upload" id="motivation-upload"  />
        </p>
        <p id="vacancy-cv-upload">
            <label for="cv-upload" class="first"><?=$this->__('Upload CV (Max 2Mb)');?>:</label>
            <input type="file" name="cv-upload" id="cv-upload" />
        </p>
        <p id="vacancy-photo-upload">
            <label for="photo-upload" class="first"><?=$this->__('Upload photo');?>:</label>
            <input type="file" name="photo-upload" id="photo-upload" />
        </p>

        <p class="footer">
            <button type="submit" id="vacancy-apply-submit">
				<span class="custom-nav custom-nav-alt"><span><?=$this->__('Submit');?></span></span>
			</button>
        </p>
    </form>
</div>