<?php

class Kega_Store_Model_Entity_Setup extends Mage_Eav_Model_Entity_Setup
{

    public function getDefaultEntities()
    {
		return array(
			'store' => array(
				'entity_model'          =>'store/store',
				'attribute_model'   	=> 'store/resource_eav_attribute',
				'table'                 => 'store/entity',
//				'increment_model'       => 'eav/entity_increment_numeric',
//				'increment_per_store'   => false,
				'attributes' => array(
                    'storenummer' => array(
						'type'          => 'varchar',
						'label'         => 'Store nummer',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 5,
					),
					'name' => array(
						'type'          => 'varchar',
						'label'         => 'Title',
						'required'      => true,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 10,
					),
					'address' => array(
						'type'          => 'varchar',
						'label'         => 'Address',
						'default'       => '',
						'required'      => true,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 20,
					),
					'number' => array(
						'type'          => 'varchar',
						'label'         => 'Number',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 22,
					),
					'number_ext' => array(
						'type'          => 'varchar',
						'label'         => 'Ext.',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 24,
					),
					'district' => array(
						'type'          => 'varchar',
						'label'         => 'District',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 30,
					),
					'city' => array(
						'type'          => 'varchar',
						'label'         => 'City',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 40,
					),
					'country_id' => array(
						'type'          => 'varchar',
						'label'         => 'Country',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 45,
					),
					'state' => array(
						'type'          => 'varchar',
						'label'         => 'State',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 50,
					),
					'zipcode' => array(
						'type'          => 'varchar',
						'label'         => 'Zipcode',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 60,
					),
					'phone' => array(
						'type'          => 'varchar',
						'label'         => 'Phone',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 70,
					),
					'fax' => array(
						'label'         => 'Fax',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 80,
					),
					'email' => array(
						'label'         => 'Email',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 90,
					),
					'lng' => array(
						'type'          => 'varchar',
						'label'         => 'Google Lng',
						'default'       => '',
						'required'      => true,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 91,
					),
					'lat' => array(
						'type'          => 'varchar',
						'label'         => 'Google Lat',
						'default'       => '',
						'required'      => true,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 92,
					),
                    'routenummer' => array(
                        'type'          => 'varchar',
						'label'         => 'Route nummer',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 93,
					),
					'hours' => array(
						'type'          => 'varchar',
						'label'         => 'Hours',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 94,
					),
					'website_url' => array(
						'label'         => 'Website url',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 100,
					),
					'custom_url' => array(
						'label'         => 'Custom url',
						'default'       => '',
						'required'      => true,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
						'sort_order'    => 110,
						'unique'        => true
					),
					'description' => array(
                        'type'              => 'text',
                        'label'             => 'Description',
                        'input'             => 'textarea',
                        'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'visible'           => true,
                        'required'          => false,
                        'user_defined'      => false,
                        'default'           => '',
                        'searchable'        => false,
                        'filterable'        => false,
                        'comparable'        => false,
                        'unique'            => false,
                    ),
                    'is_active' => array(
                        'type'              => 'int',
                        'backend'           => '',
                        'frontend'          => '',
                        'label'             => 'Is Active',
                        'input'             => 'select',
                        'class'             => '',
                        'source'            => 'eav/entity_attribute_source_boolean',
                        'global'            => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'visible'           => true,
                        'required'          => false,
                        'user_defined'      => false,
                        'default'           => '1',
                        'searchable'        => false,
                        'filterable'        => false,
                        'comparable'        => false,
                        'visible_on_front'  => false,
                        'unique'            => false,
                    ),
					'manager_name' => array(
						'label'         => 'Manager name',
						'default'       => '',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 120,
					),
					'manager_image' => array(
						'label'         => 'Manager image',
						'default'       => '',
						'input'         => 'file',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 130,
					),
					'store_image' => array(
						'label'         => 'Store image',
						'default'       => '',
						'input'         => 'file',
						'required'      => false,
						'user_defined'  => false,
						'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
						'sort_order'    => 130,
					),
				),
			),
		);
	}

}
